server:
  port: 8080

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  expiration-seconds: 7200

springdoc:
  swagger-ui:
    path: /docs
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /v3/api-docs